name: Rust-Build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    runs-on: windows-latest
    strategy:
        matrix:
          toolchain: [ "nightly" ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install
      run: rustup update ${{ matrix.toolchain }}
    - name: Select
      run: rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --release --verbose
    - name: Show Files
      run: ls
    - name: Artifact Upload
      uses: actions/upload-artifact@v3
      with:
        name: raytrace.exe
        path: main.exe
